html<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Event promote rejected</title>
</head>
<body>
	<h3>dear customer,</h3>
	your promote event test event has been rejected, please review your event.
	<ul> 
	<li>to view your event detail please click <a href="http://localhost/events/detail/?__appId=calpro&id=9">here</a> [http://localhost/events/detail/?__appId=calpro&id=9]</li> 
	<li>to view your Promote detail please click <a href="promoteurl#">here</a> [http://localhost/eventspromoted/detail/?__appId=calpro&id=3]</li> 
	
	</ul>
	<h4>System Messages :</h4>
	Invalid image
	
	<h4>Admin message:</h4>
	&nbsp;
</body>
</html>