html<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>events.message.promoterejected</title>
</head>
<body>
	<h3>dear customer,</h3>
	your promote event #event_name# has been rejected, please review your event by following this 
	<a href="http://localhost/events/detail/?__appId=calpro&id=9">link</a>
	http://localhost/events/detail/?__appId=calpro&id=9
	<h4>System Messages :</h4>
	#sysmessages#
	
	<h4>Admin message:</h4>
	#message#
</body>
</html>