INSERT INTO `language` VALUES ('en', '0', 'English', '', -1, 1);
INSERT INTO `language` VALUES ('id', '0', 'Indonesia', 'Bahasa Nasional Indonesia', -1, 1);
INSERT INTO `language` VALUES ('id-aceh', 'id', 'Aceh', 'Bahasa Aceh Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-alas', 'id', 'Alas', 'Bahasa Alas Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-alor', 'id', 'Alor', 'Bahasa Alor Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-ambelan', 'id', 'Ambelan', 'Bahasa Ambelan Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-angkola', 'id', 'Angkola', 'Bahasa Angkola Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-aru', 'id', 'Aru', 'Bahasa Aru Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-bacan', 'id', 'Bacan', 'Bahasa Bacan Digunakan di Wilayah Maluku Daerah Sekitar Sula Bacan', -1, 1);
INSERT INTO `language` VALUES ('id-badabesona', 'id', 'Bada''Besona', 'Bahasa Bada'' Besona Digunakan di Wilayah Sulawesi Daerah Sekitar Toraja', -1, 1);
INSERT INTO `language` VALUES ('id-bahau', 'id', 'Bahau', 'Bahasa Bahau Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-bajau', 'id', 'Bajau', 'Bahasa Bajau Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-balantak', 'id', 'Balantak', 'Bahasa Balantak Digunakan di Wilayah Sulawesi Daerah Sekitar Loinan', -1, 1);
INSERT INTO `language` VALUES ('id-bali', 'id', 'Bali', 'Bahasa Bali Digunakan di Wilayah Bali', -1, 1);
INSERT INTO `language` VALUES ('id-banda', 'id', 'Banda', 'Bahasa Banda Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-banggai', 'id', 'Banggai', 'Bahasa Banggai Digunakan di Wilayah Sulawesi Daerah Sekitar Loinan', -1, 1);
INSERT INTO `language` VALUES ('id-banjar', 'id', 'Banjar', 'Bahasa Banjar Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-bantik', 'id', 'Bantik', 'Bahasa Bantik Digunakan di Wilayah Sulawesi Daerah Sekitar Sulut', -1, 1);
INSERT INTO `language` VALUES ('id-batak', 'id', 'Batak', 'Bahasa Batak Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-belu', 'id', 'Belu', 'Bahasa Belu Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-betawi', 'id', 'Betawi', 'Bahasanye orang jakarte', -1, 1);
INSERT INTO `language` VALUES ('id-bobongko', 'id', 'Bobongko', 'Bahasa Bobongko Digunakan di Wilayah Sulawesi Daerah Sekitar Loinan', -1, 1);
INSERT INTO `language` VALUES ('id-bonerate', 'id', 'Bonerate', 'Bahasa Bonerate Digunakan di Wilayah Sulawesi Daerah Sekitar Muna Butung', -1, 1);
INSERT INTO `language` VALUES ('id-bugis', 'id', 'Bugis', 'Bahasa Bugis Digunakan di Wilayah Sulawesi Daerah Sekitar Sulsel', -1, 1);
INSERT INTO `language` VALUES ('id-bulanga', 'id', 'Bulanga', 'Bahasa Bulanga Digunakan di Wilayah Sulawesi Daerah Sekitar Gorontalo', -1, 1);
INSERT INTO `language` VALUES ('id-bungkumori', 'id', 'Bungkumori', 'Bahasa Bungkumori Digunakan di Wilayah Sulawesi Daerah Sekitar Bungku Langku', -1, 1);
INSERT INTO `language` VALUES ('id-buol', 'id', 'Buol', 'Bahasa Buol Digunakan di Wilayah Sulawesi Daerah Sekitar Gate', -1, 1);
INSERT INTO `language` VALUES ('id-buru', 'id', 'Buru', 'Bahasa Buru Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-butung', 'id', 'Butung', 'Bahasa Butung Digunakan di Wilayah Sulawesi Daerah Sekitar Muna Butung', -1, 1);
INSERT INTO `language` VALUES ('id-enggano', 'id', 'Enggano', 'Bahasa Enggano Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-gayo', 'id', 'Gayo', 'Bahasa Gayo Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-geloli', 'id', 'Geloli', 'Bahasa Geloli Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-goram', 'id', 'Goram', 'Bahasa Goram Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-gorontalo', 'id', 'Gorontalo', 'Bahasa Gorontalo Digunakan di Wilayah Sulawesi Daerah Sekitar Gate', -1, 1);
INSERT INTO `language` VALUES ('id-helo', 'id', 'Helo', 'Bahasa Helo Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-iban', 'id', 'Iban', 'Bahasa Iban Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-jawa', 'id', 'Jawa', 'Bahasa Jawa Digunakan di Wilayah Jawa', -1, 1);
INSERT INTO `language` VALUES ('id-kadang', 'id', 'Kadang', 'Bahasa Kadang Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-kai', 'id', 'Kai', 'Bahasa Kai Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-kaidipan', 'id', 'Kaidipan', 'Bahasa Kaidipan Digunakan di Wilayah Sulawesi Daerah Sekitar Gate', -1, 1);
INSERT INTO `language` VALUES ('id-kail', 'id', 'Kail', 'Bahasa Kail Digunakan di Wilayah Sulawesi Daerah Sekitar Toraja', -1, 1);
INSERT INTO `language` VALUES ('id-kaisar', 'id', 'Kaisar', 'Bahasa Kaisar Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-kalaotoa', 'id', 'Kalaotoa', 'Bahasa Kalaotoa Digunakan di Wilayah Sulawesi Daerah Sekitar Muna Butung', -1, 1);
INSERT INTO `language` VALUES ('id-karo', 'id', 'Karo', 'Bahasa Karo Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-karompa', 'id', 'Karompa', 'Bahasa Karompa Digunakan di Wilayah Sulawesi Daerah Sekitar Muna Butung', -1, 1);
INSERT INTO `language` VALUES ('id-kayan', 'id', 'Kayan', 'Bahasa Kayan Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-kenya', 'id', 'Kenya', 'Bahasa Kenya Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-klemautan', 'id', 'Klemautan', 'Bahasa Klemautan Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-kroe', 'id', 'Kroe', 'Bahasa Kroe Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-kubu', 'id', 'Kubu', 'Bahasa Kubu Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-lain', 'id', 'Lain', 'Bahasa Lain Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-laki', 'id', 'Laki', 'Bahasa Laki Digunakan di Wilayah Sulawesi Daerah Sekitar Bungku Langku', -1, 1);
INSERT INTO `language` VALUES ('id-lampung', 'id', 'Lampung', 'Bahasa Lampung Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-landawe', 'id', 'Landawe', 'Bahasa Landawe Digunakan di Wilayah Sulawesi Daerah Sekitar Bungku Langku', -1, 1);
INSERT INTO `language` VALUES ('id-layolo', 'id', 'Layolo', 'Bahasa Layolo Digunakan di Wilayah Sulawesi Daerah Sekitar Muna Butung', -1, 1);
INSERT INTO `language` VALUES ('id-leboni', 'id', 'Leboni', 'Bahasa Leboni Digunakan di Wilayah Sulawesi Daerah Sekitar Toraja', -1, 1);
INSERT INTO `language` VALUES ('id-leti', 'id', 'Leti', 'Bahasa Leti Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-loinan', 'id', 'Loinan', 'Bahasa Loinan Digunakan di Wilayah Sulawesi Daerah Sekitar Loinan', -1, 1);
INSERT INTO `language` VALUES ('id-lom', 'id', 'Lom', 'Bahasa Lom Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-luwu', 'id', 'Luwu', 'Bahasa Luwu Digunakan di Wilayah Sulawesi Daerah Sekitar Sulsel', -1, 1);
INSERT INTO `language` VALUES ('id-madura', 'id', 'Madura', 'Bahasa Madura Digunakan di Wilayah Jawa', -1, 1);
INSERT INTO `language` VALUES ('id-makassar', 'id', 'Makassar', 'Bahasa Makassar Digunakan di Wilayah Sulawesi Daerah Sekitar Sulsel', -1, 1);
INSERT INTO `language` VALUES ('id-mandailing', 'id', 'Mandailing', 'Bahasa Mandailing Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-mandar', 'id', 'Mandar', 'Bahasa Mandar Digunakan di Wilayah Sulawesi Daerah Sekitar Sulsel', -1, 1);
INSERT INTO `language` VALUES ('id-mapute', 'id', 'Mapute', 'Bahasa Mapute Digunakan di Wilayah Sulawesi Daerah Sekitar Bungku Langku', -1, 1);
INSERT INTO `language` VALUES ('id-melayu', 'id', 'Melayu', 'Bahasa Melayu Digunakan di Wilayah Kalimantan & Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-mentawai', 'id', 'Mentawai', 'Bahasa Mentawai Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-milano', 'id', 'Milano', 'Bahasa Milano Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-minangkabau', 'id', 'Minangkabau', 'Bahasa Minangkabau Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-mongondow', 'id', 'Mongondow', 'Bahasa Mongondow Digunakan di Wilayah Sulawesi Daerah Sekitar Sulut', -1, 1);
INSERT INTO `language` VALUES ('id-napu', 'id', 'Napu', 'Bahasa Napu Digunakan di Wilayah Sulawesi Daerah Sekitar Toraja', -1, 1);
INSERT INTO `language` VALUES ('id-nias', 'id', 'Nias', 'Bahasa Nias Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-orang', 'id', 'Orang', 'Bahasa Orang Laut Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-ot-danum', 'id', 'Ot-Danum', 'Bahasa Ot-Danum Digunakan di Wilayah Kalimantan', -1, 1);
INSERT INTO `language` VALUES ('id-pak-pak', 'id', 'Pak-Pak', 'Bahasa Pak-Pak Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-pantar', 'id', 'Pantar', 'Bahasa Pantar Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-pilpikoro', 'id', 'Pilpikoro', 'Bahasa Pilpikoro Digunakan di Wilayah Sulawesi Daerah Sekitar Toraja', -1, 1);
INSERT INTO `language` VALUES ('id-pitu', 'id', 'Pitu', 'Bahasa Pitu Digunakan di Wilayah Sulawesi Daerah Sekitar Sulsel', -1, 1);
INSERT INTO `language` VALUES ('id-rejang', 'id', 'Rejang', 'Bahasa Rejang Lebong Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-riau', 'id', 'Riau', 'Bahasa Riau Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-roma', 'id', 'Roma', 'Bahasa Roma Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-rote', 'id', 'Rote', 'Bahasa Rote Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-sadan', 'id', 'Sa''dan', 'Bahasa Sa''dan Digunakan di Wilayah Sulawesi Daerah Sekitar Sulsel', -1, 1);
INSERT INTO `language` VALUES ('id-salu', 'id', 'Salu', 'Bahasa Salu Digunakan di Wilayah Sulawesi Daerah Sekitar Sulsel', -1, 1);
INSERT INTO `language` VALUES ('id-sangir', 'id', 'Sangir', 'Bahasa Sangir Digunakan di Wilayah Sulawesi Daerah Sekitar Sulut', -1, 1);
INSERT INTO `language` VALUES ('id-sasak-bali', 'id', 'Sasak', 'Bahasa Sasak Digunakan di Wilayah Bali', -1, 1);
INSERT INTO `language` VALUES ('id-sasak-ntb', 'id', 'Sasak', 'Bahasa Sasak Digunakan di Wilayah Nusa Tenggara Barat', -1, 1);
INSERT INTO `language` VALUES ('id-sasak-ntt', 'id', 'Sasak', 'Bahasa Sasak Digunakan di Wilayah Nusa Tenggara Timur', -1, 1);
INSERT INTO `language` VALUES ('id-seko', 'id', 'Seko', 'Bahasa Seko Digunakan di Wilayah Sulawesi Daerah Sekitar Sulsel', -1, 1);
INSERT INTO `language` VALUES ('id-sikule', 'id', 'Sikule', 'Bahasa Sikule Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-simulur', 'id', 'Simulur', 'Bahasa Simulur Digunakan di Wilayah Sumatera', -1, 1);
INSERT INTO `language` VALUES ('id-solor', 'id', 'Solor', 'Bahasa Solor Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-sula', 'id', 'Sula', 'Bahasa Sula Digunakan di Wilayah Maluku Daerah Sekitar Sula Bacan', -1, 1);
INSERT INTO `language` VALUES ('id-sumba', 'id', 'Sumba', 'Bahasa Sumba Digunakan di Wilayah Nusa Tenggara Barat', -1, 2);
INSERT INTO `language` VALUES ('id-sumbawa', 'id', 'Sumbawa', 'Bahasa Sumbawa Digunakan di Wilayah Nusa Tenggara Timur', -1, 1);
INSERT INTO `language` VALUES ('id-sunda', 'id', 'Sunda', 'Bahasa Sunda Digunakan di Wilayah Jawa', -1, 1);
INSERT INTO `language` VALUES ('id-sunda-ngalagena', 'id-sunda', 'Sunda ngalagena', 'bahasa sunda yang digunakan dijaman dulu', -1, 1);
INSERT INTO `language` VALUES ('id-talaud', 'id', 'Talaud', 'Bahasa Talaud Digunakan di Wilayah Sulawesi Daerah Sekitar Sulut', -1, 1);
INSERT INTO `language` VALUES ('id-taliabo', 'id', 'Taliabo', 'Bahasa Taliabo Digunakan di Wilayah Maluku Daerah Sekitar Sula Bacan', -1, 1);
INSERT INTO `language` VALUES ('id-tambulu', 'id', 'Tambulu', 'Bahasa Tambulu Digunakan di Wilayah Sulawesi Daerah Sekitar Sulut', -1, 1);
INSERT INTO `language` VALUES ('id-tanibar', 'id', 'Tanibar', 'Bahasa Tanibar Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-ternate', 'id', 'Ternate', 'Bahasa Ternate Digunakan di Wilayah Maluku Daerah Sekitar Halmahera Utara', -1, 1);
INSERT INTO `language` VALUES ('id-tetun-ambon', 'id', 'Tetun', 'Bahasa Tetun Digunakan di Wilayah Maluku Daerah Sekitar Ambon Timur', -1, 1);
INSERT INTO `language` VALUES ('id-tetun-ntt', 'id', 'Tetun', 'Bahasa Tetun Digunakan di Wilayah Nusa Tenggara Timur', -1, 1);
INSERT INTO `language` VALUES ('id-tidore', 'id', 'Tidore', 'Bahasa Tidore Digunakan di Wilayah Maluku Daerah Sekitar Halmahera Utara', -1, 1);
INSERT INTO `language` VALUES ('id-timor', 'id', 'Timor', 'Bahasa Timor Digunakan di Wilayah Nusa Tenggara Timur', -1, 1);